### ISSUE TITLE
cannot find module 'precss'

### ISSUE THREAD

**Issue by lihaoqi1991** [vuejs/vue-loader#1004]
### Version
13.3.0

### Steps to reproduce
when I update the vue-loader from 13.0.4 to 13.3.0, webpack npm run dev occurs an error 
ERROR in ./node_modules/_css-loader@0.28.7@css-loader!./node_modules/_vue-loader@13.3.0@vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-c284b4c0","scoped":true,"hasInlineConfig":true}!./node_modules/_less-loader@2.2.3@less-loader!./node_modules/_vue-loader@13.3.0@vue-loader/lib/selector.js?type=styles&index=0&bustCache!./src/components/structure/datetime/index.vue
Cannot find module 'precss'

### What is expected?
no error when npm run dev using vue-loader13.3.0

### What is actually happening?
error in vue-loader13.3.0
