### ISSUE TITLE
Error after updating webpack from 5.47.1 to 5.48.0 (Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin')

### ISSUE THREAD

**Issue by dsine-de** [vuejs/vue-loader#1859]
### Version
16.3.3

### Reproduction link
[https://github.com/dsine-de/vue-loader-webpack-update](https://github.com/dsine-de/vue-loader-webpack-update)

### Steps to reproduce
Clone the repo & run "npm i", then run "npm run dev" (or "npx webpack")

### What is expected?
There should not be an error: "Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'"

### What is actually happening?
```
[webpack-cli] Failed to load 'C:\repositories\vue-loader-webpack-update\webpack.config.cjs' config
[webpack-cli] Error: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'
Require stack:
- C:\repositories\vue-loader-webpack-update\node_modules\vue-loader\lib\plugin-webpack5.js
- C:\repositories\vue-loader-webpack-update\node_modules\vue-loader\lib\plugin.js
- C:\repositories\vue-loader-webpack-update\node_modules\vue-loader\lib\index.js
- C:\repositories\vue-loader-webpack-update\webpack.config.cjs
- C:\repositories\vue-loader-webpack-update\node_modules\webpack-cli\lib\webpack-cli.js
- C:\repositories\vue-loader-webpack-update\node_modules\webpack-cli\lib\bootstrap.js
- C:\repositories\vue-loader-webpack-update\node_modules\webpack-cli\bin\cli.js
- C:\repositories\vue-loader-webpack-update\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\repositories\vue-loader-webpack-update\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\repositories\vue-loader-webpack-update\node_modules\vue-loader\lib\plugin-webpack5.js:6:42)
    at Module._compile (C:\repositories\vue-loader-webpack-update\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\repositories\\vue-loader-webpack-update\\node_modules\\vue-loader\\lib\\plugin-webpack5.js',
    'C:\\repositories\\vue-loader-webpack-update\\node_modules\\vue-loader\\lib\\plugin.js',
    'C:\\repositories\\vue-loader-webpack-update\\node_modules\\vue-loader\\lib\\index.js',
    'C:\\repositories\\vue-loader-webpack-update\\webpack.config.cjs',
    'C:\\repositories\\vue-loader-webpack-update\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'C:\\repositories\\vue-loader-webpack-update\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'C:\\repositories\\vue-loader-webpack-update\\node_modules\\webpack-cli\\bin\\cli.js',
    'C:\\repositories\\vue-loader-webpack-update\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
```

**Comment by dsine-de** [comment]
I'm on Windows 10 btw.

**Comment by ScottAtRedHawk** [comment]
Same for me on macOS Big Sur 11.15.1.

**Comment by WaqasIbrahim** [comment]
Same for me on Linux (Manjaro).

**Comment by bbonch** [comment]
Same for me on Windows 10. Have to deploy manually until fixed.

**Comment by erickpasar** [comment]
I update the Vue. Works Great for me!

npm vue-loader

**Comment by GhostMech** [comment]
This also resolve my issue with Webpack and Vue 2.

**Comment by Iloba** [comment]
`npm i vue-loader` worked for me

**Comment by 0x15f** [comment]
> I am a Laravel user.
> `npm i vue-loader` updated Vue-loader from 15.9.6 to 15.9.8 fixed this for me using Laravel 7.30.4 and Vue 2.6.12
> 
> ```
>         "vue": "^2.6.12",
>         "vue-loader": "^15.9.8",
> ```

This worked for me as well!

**Comment by IqraMalik496** [comment]
updating vue-loader worked for me as well

**Comment by RoshanJafri** [comment]
npm i vue-loader worked for me.

**Comment by mspaini** [comment]
npm i vue-loader  worked for me too--laravel 8 w10

**Comment by daviddelusenet** [comment]
I'm using vue-loader version `16.5.0` in combination with webpack version `5.51.1` and running into this error. Running `npm i vue-loader` doesn't do anything for me.

Any other suggestions?

Node version: `15.14.0`
NPM version: `7.16.0`

**Comment by claudionunezjr** [comment]
Also getting this error, but fixed it. Installed dependencies before the fix...
deps: `"vue": "^3.2.6"`
devDeps:
```
"@vue/compiler-sfc": "^3.1.2",
"vue-loader": "16.2.0",
"webpack": "^5.39.0",
"webpack-cli": "^4.7.2"
```

After the fix...
deps: `"vue": "^3.2.6"`
devDeps:
```
"@vue/compiler-sfc": "^3.2.6,
"vue-loader": "^15.9.8",
"webpack": "^5.39.0",
"webpack-cli": "^4.7.2"
```

Notice the `vue-loader` version - this is what fixed it for me. And I updated `@vue/compiler-sfc` to match the `vue` version.

**Comment by marcmosobo** [comment]
npm i vue-loader worked for me too win10 laravel8

**Comment by aliyenigunn** [comment]
I solved just with npm update (win10 and laravel8)

**Comment by Majidkadi** [comment]
I have had same error and solved it by running:
npm update

**Comment by leonardo403** [comment]
I have same error. 
Solution problem => `npm i vue-loader`

**Comment by DustinJoosen** [comment]
> I am a Laravel user.
> `npm i vue-loader` updated Vue-loader from 15.9.6 to 15.9.8 fixed this for me using Laravel 7.30.4 and Vue 2.6.12
> 
> ```
>         "vue": "^2.6.12",
>         "vue-loader": "^15.9.8",
> ```

It worked for me! thanks so much!

**Comment by daviidy** [comment]
> `npm i vue-loader` worked for me

Same for me. Thank you

**Comment by BarasaK** [comment]
> I am a Laravel user.
> `npm i vue-loader` updated Vue-loader from 15.9.6 to 15.9.8 fixed this for me using Laravel 7.30.4 and Vue 2.6.12
> 
> ```
>         "vue": "^2.6.12",
>         "vue-loader": "^15.9.8",
> ```

npm i vue-loader worked for me

**Comment by Otisssss** [comment]
@BarasaK thank you. Laravel 8

**Comment by victoralonsopacha** [comment]
I have the same error, laravel 8, I use: npm update

**Comment by mdanish98** [comment]
`npm i vue-loader` also worked for me

Thanks a lot

**Comment by AB7zz** [comment]
`npm i vue-loader` worked for me too

**Comment by tripleten** [comment]
Running npm i vue-loader fixed the issue for me as well for L8 on Win10.

**Comment by andrey-helldar** [comment]
Works for me with VieJS 3:

```json
{
    "dependencies": {
        "@babel/plugin-proposal-optional-chaining": "^7.16.0",
        "vue": "^3.2.20"
    },
    "devDependencies": {
        "@vue/compiler-sfc": "^3.2.20",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "postcss": "^8.1.14",
        "resolve-url-loader": "^4.0.0",
        "sass": "^1.43.4",
        "sass-loader": "^12.1.0",
        "vue-loader": "^16.2.0"
    }
}
```

**Comment by jamesmerize** [comment]
> I am a Laravel user. `npm i vue-loader` updated Vue-loader from 15.9.6 to 15.9.8 fixed this for me using Laravel 7.30.4 and Vue 2.6.12
> 
> ```
>         "vue": "^2.6.12",
>         "vue-loader": "^15.9.8",
> ```

This solve my issue. Thank you

**Comment by rasyidialwee** [comment]
> I am a Laravel user. `npm i vue-loader` updated Vue-loader from 15.9.6 to 15.9.8 fixed this for me using Laravel 7.30.4 and Vue 2.6.12
> 
> ```
>         "vue": "^2.6.12",
>         "vue-loader": "^15.9.8",
> ```

nice this work for me too

**Comment by ihsan-khan** [comment]
> ### Version
> 16.3.3
> 
> ### Reproduction link
> https://github.com/dsine-de/vue-loader-webpack-update
> 
> ### Steps to reproduce
> Clone the repo & run "npm i", then run "npm run dev" (or "npx webpack")
> 
> ### What is expected?
> There should not be an error: "Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'"
> 
> ### What is actually happening?
> ```
> [webpack-cli] Failed to load 'C:\repositories\vue-loader-webpack-update\webpack.config.cjs' config
> [webpack-cli] Error: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'
> Require stack:
> - C:\repositories\vue-loader-webpack-update\node_modules\vue-loader\lib\plugin-webpack5.js
> - C:\repositories\vue-loader-webpack-update\node_modules\vue-loader\lib\plugin.js
> - C:\repositories\vue-loader-webpack-update\node_modules\vue-loader\lib\index.js
> - C:\repositories\vue-loader-webpack-update\webpack.config.cjs
> - C:\repositories\vue-loader-webpack-update\node_modules\webpack-cli\lib\webpack-cli.js
> - C:\repositories\vue-loader-webpack-update\node_modules\webpack-cli\lib\bootstrap.js
> - C:\repositories\vue-loader-webpack-update\node_modules\webpack-cli\bin\cli.js
> - C:\repositories\vue-loader-webpack-update\node_modules\webpack\bin\webpack.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (C:\repositories\vue-loader-webpack-update\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
>     at Object.<anonymous> (C:\repositories\vue-loader-webpack-update\node_modules\vue-loader\lib\plugin-webpack5.js:6:42)
>     at Module._compile (C:\repositories\vue-loader-webpack-update\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'C:\\repositories\\vue-loader-webpack-update\\node_modules\\vue-loader\\lib\\plugin-webpack5.js',
>     'C:\\repositories\\vue-loader-webpack-update\\node_modules\\vue-loader\\lib\\plugin.js',
>     'C:\\repositories\\vue-loader-webpack-update\\node_modules\\vue-loader\\lib\\index.js',
>     'C:\\repositories\\vue-loader-webpack-update\\webpack.config.cjs',
>     'C:\\repositories\\vue-loader-webpack-update\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
>     'C:\\repositories\\vue-loader-webpack-update\\node_modules\\webpack-cli\\lib\\bootstrap.js',
>     'C:\\repositories\\vue-loader-webpack-update\\node_modules\\webpack-cli\\bin\\cli.js',
>     'C:\\repositories\\vue-loader-webpack-update\\node_modules\\webpack\\bin\\webpack.js'
>   ]
> }
> ```

i am facing same issue resolve by running following commond
npm update vue-loader

**Comment by Sacef** [comment]
Corre este comando npm install -g @vue/cli

**Comment by alcarazolabs** [comment]
I fixed this problem running: 
`npm update vue-loader`
