### ISSUE TITLE
bc break: v15.10.0 does not respect "resolve.modules" webpack configuration

### ISSUE THREAD

**Issue by boutell** [vuejs/vue-loader#1977]
Version 15.10.0 will not load `vue-template-compiler` if it is a dependency of an npm linked module in the project, even if `resolve.modules` in webpack is explicitly configured to make that possible The following error results:

```
Error: Cannot find module 'vue-template-compiler'
```

We use `resolve.modules` to support situations where the module that depends on vue-loader is npm linked into a project and/or the project has a dependency on a different version of vue-loader and thus has a separate, unwanted copy in its top level `node_modules` from our point of view. Here's an example "resolve.modules" configuration that works with 15.9.8:

```
    resolve: {
      extensions: [ '*', '.js', '.vue', '.json' ],
      modules: [
        'node_modules',
        `${apos.npmRootDir}/node_modules/apostrophe/node_modules`,
        `${apos.npmRootDir}/node_modules`
      ]
    },
```

This appears to be due to the introduction of the new `resolveCompiler` mechanism in some way.

We're pinned on the 15.9.* series for now.

Thanks for your hard work on vue and vue-loader! It is appreciated.
